name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x
      GRAPHQL_VERSION: 16
    steps:
      - uses: actions/checkout@v2
      - name: Use node-${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run lint
      - run: npm test

  versions:
    name: node-${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node: [ '12.x', '14.x', '16.x' ]
        graphql: [ '14', '15', '16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Use node-${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm test
        env:
          GRAPHQL_VERSION: ${{ matrix.graphql }}
